### ISSUE TITLE
upgrade cesium

### ISSUE THREAD

**Issue by mgiraldo** [NYPL/pic-app#104]
v1.19 is available now

**Comment by DavidRLowe** [comment]
So what new bells & whistles do we get?!

**Comment by mgiraldo** [comment]
fastness: pic.nypl.org/map/?mode=3

Mauricio Giraldo
NYPL Labs
The New York Public Library
@mgiraldo

**Comment by DavidRLowe** [comment]
not loading for me at all right now

**Comment by DavidRLowe** [comment]
nevermind, loaded.
