### ISSUE TITLE
add a text version of the facets applied

### ISSUE THREAD

**Issue by mgiraldo** [NYPL/pic-app#17]
eg: 12,358 locations for English photographers that workerd with daguerreotype

**Comment by DavidRLowe** [comment]
Really? I'm seeing very different #s... I see a total of 11159 daguerreotypists' locations (any Nationality or country).

**Comment by mgiraldo** [comment]
it's an example of how the text would look

**Comment by DavidRLowe** [comment]
ok sorry. as you were!
