### ISSUE TITLE
sort addresses by date

### ISSUE THREAD

**Issue by mgiraldo** [NYPL/pic-app#24]
when connecting them

see: Richard F. Gordon, Jr.

**Comment by mgiraldo** [comment]
this happens because sorting in JS is not by date... need to update the Python script to generate latlons sorted by date to avoid having to sort in JS at all

**Comment by DavidRLowe** [comment]
uh oh, Hamilton Campbell was born in West Virginia, died in northwest Mexico... then went on to work up and down California & Oregon.

**Comment by mgiraldo** [comment]
yes. that's the bug
