### ISSUE TITLE
Using time filter returns points, but with zero constituents

### ISSUE THREAD

**Issue by DavidRLowe** [NYPL/pic-app#45]
Example: http://mgiraldo.github.io/pic/?address.AddressTypeID=7&address.CountryID=1&Nationality=*&gender.TermID=*&process.TermID=*&role.TermID=*&format.TermID=*&biography.TermID=*&collection.TermID=2028165&Location=*&DisplayName=*&Date=[1955%20TO%201960]

I'm guessing these are for constituents who were alive or active 1955-1960, but these locations are, themselves, out of range? When you click on one of the ghost points, it and all others disappear.

**Comment by mgiraldo** [comment]
good hunch

**Comment by mgiraldo** [comment]
this seems fixed to me... i get 109 constituents with 922 locations... might have been a temporary indexing bug, something to do with the CSV

**Comment by DavidRLowe** [comment]
Cool. I'll play with it. Out for most of today.

**Comment by mgiraldo** [comment]
seems solved to me... reopen if not
