### ISSUE TITLE
Logic issues with "alive or active"

### ISSUE THREAD

**Issue by DavidRLowe** [NYPL/pic-app#61]
The time delimiter is not applied to other filters as I'd expect. For example, I'd think
Female + Birth Location + Within Bound (South America)+ Between 1900-1910
would give me Females who were born in South America between 1900&1910. Instead I get 6 results with one location: Females with a birth location and anything in 1900-1910 and anything in South America.... 
http://pic.herokuapp.com/map/?address.AddressTypeID=5&address.CountryID=*&Nationality=*&gender.TermID=2027998&process.TermID=*&role.TermID=*&format.TermID=*&biography.TermID=*&collection.TermID=*&bbox=-85.9747_-42.5218_-25.3107_4.9248&DisplayName=*&Date=[1900%20TO%201910]

**Comment by mgiraldo** [comment]
i think i nailed it. this was a painful bug 😓

**Comment by DavidRLowe** [comment]
I guess it's a different issue, sorry! I assume that when I select Location
Type Birth, Dates 1900-1910, I'd expect people Born between 1900-1910.
Sorry I'm not catching this behavior til now! I guess it would be "Alive or
Active" if I have "Any" selected, but otherwise....
Ex., I want PIC to show me American studio locations from 1900-1901. (I
hope this isn't a huge rewrite, sorry).

**Comment by mgiraldo** [comment]
hmmm... so you want the address date to take precedence over the constituent's date if there is a selection criteria for addresses (country, type)?

**Comment by DavidRLowe** [comment]
Yeah, basically.
