### ISSUE TITLE
add sorting to queries

### ISSUE THREAD

**Issue by mgiraldo** [NYPL/pic-app#7]
and give precedence to `ConstituentID` if applied

see: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html

**Comment by DavidRLowe** [comment]
Not sure I fully understand the link, but yes sorting could help.

**Comment by DavidRLowe** [comment]
What if I start with no search criteria, but it gave (the first 20) of a
list of everybody. That's not very useful, but if I limit to to Female,
Tintype, name : Smith, then I have a list of options without clicking
points on the map.... That's pretty useful.

**Comment by DavidRLowe** [comment]
(& will probably push us to 3 minutes to load!)

**Comment by mgiraldo** [comment]
I am adding "issues" to the repository so that I remember to implement them 

as a sort of to-do list

you can ignore those emails (github has an option to disable those notifications)

people use that to submit bugs and stuff like that

you can add issues too and we can keep track of stuff that way

**Comment by mgiraldo** [comment]
you mean like anticipating the result count as you type a query?
- mga
