### ISSUE TITLE
solve "south american"  nationality? " american"s show up in the results

### ISSUE THREAD

**Issue by mgiraldo** [NYPL/pic-app#89]

**Comment by DavidRLowe** [comment]
I'm fixing this in TMS, no need to program it away! (Thanks, ULAN
http://www.getty.edu/vow/ULANFullDisplay?find=Gustavo+C%C3%A1ceres&role=&nation=&prev_page=1&subjectid=500340513
)

On Mon, Mar 21, 2016 at 10:39 AM, Mauricio Giraldo <notifications@github.com
