### ISSUE TITLE
Names list when any facet applied

### ISSUE THREAD

**Issue by DavidRLowe** [NYPL/pic-app#9]
List all names when a search and/or facet is applied. Will allow for a more systematic search for a photographer when little info is known (ie. a cabinet card marked "Miss Smith" at 105 Main Street- no city given)

**Comment by mgiraldo** [comment]
not understanding. list them where?

**Comment by DavidRLowe** [comment]
In the column, just as if you clicked a point.

**Comment by mgiraldo** [comment]
hmm... this might be an issue when the facet is "Any"... 100k+ names there... lemme think... if you also have ideas, shoot

**Comment by DavidRLowe** [comment]
Well, when any other than Any. It still could be a large number, though....
You said you were trying to slow it down!

**Comment by mgiraldo** [comment]
slow it down in the updating but not for the user 💀
