### ISSUE TITLE
start date being lowest year found

### ISSUE THREAD

**Issue by mgiraldo** [NYPL/pic-app#90]

**Comment by mgiraldo** [comment]
@DavidRLowe can you add a new `min_year.csv` (or similar) file that contains only the lowest year found in the DB?

`SELECT MIN(BeginDate) FROM Constituents` or something like that should do it

you need to `git add min_year.csv` before committing and pushing the repo

once that file is there i can use it to find out the lowest number to put in the date range

**Comment by mgiraldo** [comment]
never mind... i think i should probably do this… won't give it very high priority, though

**Comment by subsublibrary** [comment]
Agree it's a lower priority, but it would be cool to get to this before launch. I think the 1700 does seem a little odd. I also think it's nice that if we can use the lowest number from the data set, the defaults organically give you a time range (from a biographical perspective) of the history of photography.

**Comment by mgiraldo** [comment]
working on it right now

Mauricio Giraldo
NYPL Labs
The New York Public Library
@mgiraldo

**Comment by DavidRLowe** [comment]
Drumroll, pls, earliest non-zero start year: _Johann Heinrich Schulze
https://en.wikipedia.org/wiki/Johann_Heinrich_Schulze (_1687 – 1744).
also in the Encyclopedia of Nineteenth Century Photography.

**Comment by subsublibrary** [comment]
Holy smokes!

**Comment by DavidRLowe** [comment]
Basically made photos but couldn't "fix" them. That's why there's a case to
made that something from Thomas Wedgwood could turn up & unseat niepce as
the first true photographer. Not that likely, but...

**Comment by mgiraldo** [comment]
i am getting a 19 (in address.csv) and a 190 (in constituents.csv) as smallest years

**Comment by DavidRLowe** [comment]
fixing now

**Comment by mgiraldo** [comment]
testing now with the current years...

you will see the minimum years found in the [travis log](https://travis-ci.org/NYPL/pic-data)

like:

<img width="322" alt="minyear" src="https://cloud.githubusercontent.com/assets/133020/14000247/c040529a-f116-11e5-8b76-0e9f6b16cea9.png">

**Comment by DavidRLowe** [comment]
pushing through with corrected dates in a sec

**Comment by mgiraldo** [comment]
fixed in 86cb35d5c21ceadf369204b4cf20c0657d1d3bdf

**Comment by DavidRLowe** [comment]
and it worked!

Minimum year in address is: 1687

Minimum year in constituents is: 1687
