### ISSUE TITLE
Some search tuning needed (e.g. Man Ray)

### ISSUE THREAD

**Issue by subsublibrary** [NYPL/pic-app#94]
Search for "Man Ray", you get 99 constituents. Assumed Man Ray himself would be top result, but he's actually around number 77.

**Comment by mgiraldo** [comment]
this is because "Man Ray" is lower in A-Z order vs "May Golding" and company

it is a slippery slope because i could make it return more exact matches only but then we lose stephen and steven etc.

there could be further exploration on text search refinements

**Comment by subsublibrary** [comment]
Is there a refinement that just privileges a direct match, but remains flexible with the rest?

**Comment by mgiraldo** [comment]
will work on it

**Comment by DavidRLowe** [comment]
I think that's pretty good: after a point of fuzziness it reverts back to
the alphabetical list.
