### ISSUE TITLE
Slight adjustment on zoom level for connected locations

### ISSUE THREAD

**Issue by subsublibrary** [NYPL/pic-app#95]
Small thing, but it would be nice to add a tiny bit of buffer when viewing connected locations. For example here:

![screen shot 2016-03-23 at 4 53 28 pm](https://cloud.githubusercontent.com/assets/1590897/14000491/d87a7f74-f117-11e5-9fd2-6684fcb54887.png)

The furthest out points are right at the edge of the map. Would be nice to have it more like this:

![screen shot 2016-03-23 at 4 54 37 pm](https://cloud.githubusercontent.com/assets/1590897/14000538/03bf004c-f118-11e5-9e93-d087eaec731a.png)

**Comment by mgiraldo** [comment]
yeah i've been trying to accomodate this request but the padding varies depending on zoom level:

if all results are in brooklyn, the padding is, say, 500m

if results are in europe and asia, padding is 500km

so it is not an easy fix... right now i am making sure that results are visible but sometimes it is very tight, if the line is very horizontal

**Comment by subsublibrary** [comment]
Ok, definitely not a showstopper.

**Comment by DavidRLowe** [comment]
Ok! that seems to keep it all on screen!
